### ISSUE TITLE
你好，这个国密，前端应该怎么编写啊

### ISSUE THREAD

**Issue by 183demao** [njk888/SM2#4]
您好，后端亲测可以使用，但是前端的加密后转到后面，无法解包，请问有推荐的前端库吗

**Comment by njk888** [comment]
好久没看了 解决了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月24日(周二) 晚上7:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [njk888/SM2] 你好，这个国密，前端应该怎么编写啊 (Issue #4)




 
您好，后端亲测可以使用，但是前端的加密后转到后面，无法解包，请问有推荐的前端库吗

**Comment by 183demao** [comment]
已经解决了，感谢！！
